name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests and generate coverage report
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          go test ./test/... -v -coverprofile=coverage.txt -coverpkg=./limiter,./middleware

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Token is optional for public repos
          file: coverage.txt
          slug: felipegenef/post-graduation-exercise-rate-limiter
